### ISSUE TITLE
Property read error when rendering NPC sheet

### ISSUE THREAD

**Issue by thompsonphys** [zeel01/MonsterBlocks#21]
Running with v2.2.2 in FVTT 0.7.5, I've started seeing MonsterBlocks throw the following error upon the opening of particular monster sheets:
```js
foundry.js:4406 TypeError: An error occurred while rendering MonsterBlock5e 62: Cannot read property 'toLowerCase' of null
    at MonsterBlock5e.listsPassPercept (monsterblock.js:483)
    at MonsterBlock5e.getData (monsterblock.js:57)
    at MonsterBlock5e._render (foundry.js:4434)
    at MonsterBlock5e._render (foundry.js:5088)
    at MonsterBlock5e._render (foundry.js:16570)
    at MonsterBlock5e.render (foundry.js:4404)
    at MonsterBlock5e.render (foundry.js:5553)
    at ActorDirectory._onClickEntityName (foundry.js:16051)
    at ActorDirectory._onClickEntityName (foundry.js:25134)
    at HTMLOListElement.dispatch (jquery.min.js:2)
    at HTMLOListElement.v.handle (jquery.min.js:2)
```
This seems to be an error when calling the value of the NPC's passive perception. The monster blocks that I'm trying to open were grabbed from DNDBeyond using VTTAssets, but this happens with freshly-made NPCs as well. Not every NPC block gives this error, but e.g. the `Grung` or `Lizardfolk Shaman` sheets seem to be reproducing the error.

As an example, I can reproduce the error doing the following:

1. Create NPC actor.
2. Load the MonsterBlocks module.
3. Open the NPC sheet.
4. Close the NPC sheet and attempt to re-open it.

I have no difficulties opening the NPC sheet if MonsterBlocks is then disabled. Also, steps 1 and 2 are interchangable.

Please let me know if there's anything else needed to help with debugging!

**Comment by zeel01** [comment]
This one is on my radar. It might be caused by a change in 0.7.5, or
something in the latest 5e. I'm seeing `null` values in places that should
just be empty strings `""` which causes an error particularly for senses.
If the creature has senses, no error, but if it has no special senses it
causes an error.

It's not hard to prevent the error, but I want to verify that there isn't
something deeper wrong with thr sheet, 5e, or Core before releasing a fix.

**Comment by zeel01** [comment]
Fixed in version 2.2.5

**Comment by adougherty** [comment]
Unfortunately, this problem still persists, just on a different line, and different function

```
foundry.js:4406 TypeError: An error occurred while rendering MonsterBlock5e 91: Cannot read property 'editing' of undefined
    at MonsterBlock5e.getData (monsterblock.js:67)
    at MonsterBlock5e._render (foundry.js:4434)
    at MonsterBlock5e._render (foundry.js:5088)
    at MonsterBlock5e._render (foundry.js:16570)
    at MonsterBlock5e.render (foundry.js:4404)
    at MonsterBlock5e.render (foundry.js:5553)
    at Token._onClickLeft2 (foundry.js:44654)
    at MouseInteractionManager.callback (foundry.js:35797)
    at MouseInteractionManager._handleClickLeft2 (foundry.js:35999)
    at MouseInteractionManager._handleMouseDown (foundry.js:35961)
```

**Comment by zeel01** [comment]
That one is a different issue. Is there anything above that? Any other
errors or warnings?

**Comment by adougherty** [comment]
Yikes, my apologies for adding to the wrong bug. Here is the complete debug log

```
foundry.js:4428 Foundry VTT | Rendering HealthEstimateOverlay
foundry.js:4428 Foundry VTT | Rendering HealthEstimateOverlay
foundry.js:4428 Foundry VTT | Rendering MonsterBlock5e
monsterblock.js:64 Unexpected token u in JSON at position 0
getData @ monsterblock.js:64
_render @ foundry.js:4434
_render @ foundry.js:5088
_render @ foundry.js:16570
render @ foundry.js:4404
render @ foundry.js:5553
_onClickLeft2 @ foundry.js:44654
callback @ foundry.js:35797
_handleClickLeft2 @ foundry.js:35999
_handleMouseDown @ foundry.js:35961
a.emit @ index.js:181
r.dispatchEvent @ InteractionManager.ts:1106
r.processPointerDown @ InteractionManager.ts:1307
t.recursiveFindHit @ TreeSearch.ts:173
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.findHit @ TreeSearch.ts:200
r.processInteractive @ InteractionManager.ts:1177
r.onPointerDown @ InteractionManager.ts:1252
foundry.js:4406 TypeError: An error occurred while rendering MonsterBlock5e 92: Cannot read property 'editing' of undefined
    at MonsterBlock5e.getData (monsterblock.js:67)
    at MonsterBlock5e._render (foundry.js:4434)
    at MonsterBlock5e._render (foundry.js:5088)
    at MonsterBlock5e._render (foundry.js:16570)
    at MonsterBlock5e.render (foundry.js:4404)
    at MonsterBlock5e.render (foundry.js:5553)
    at Token._onClickLeft2 (foundry.js:44654)
    at MouseInteractionManager.callback (foundry.js:35797)
    at MouseInteractionManager._handleClickLeft2 (foundry.js:35999)
    at MouseInteractionManager._handleMouseDown (foundry.js:35961)
(anonymous) @ foundry.js:4406
Promise.catch (async)
render @ foundry.js:4404
render @ foundry.js:5553
_onClickLeft2 @ foundry.js:44654
callback @ foundry.js:35797
_handleClickLeft2 @ foundry.js:35999
_handleMouseDown @ foundry.js:35961
a.emit @ index.js:181
r.dispatchEvent @ InteractionManager.ts:1106
r.processPointerDown @ InteractionManager.ts:1307
t.recursiveFindHit @ TreeSearch.ts:173
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.findHit @ TreeSearch.ts:200
r.processInteractive @ InteractionManager.ts:1177
r.onPointerDown @ InteractionManager.ts:1252
foundry.js:4428 Foundry VTT | Rendering HealthEstimateOverlay
```

**Comment by zeel01** [comment]
`monsterblock.js:64 Unexpected token u in JSON at position 0`

This error... Crap. I tried to fix it, but I might have made it worse.

**Comment by zeel01** [comment]
Okay, it should be as it was before. An error throws, but the sheet should render anyway now.

**Comment by adougherty** [comment]
Unfortunately, not :(

foundry.js:4428 Foundry VTT | Rendering MonsterBlock5e
foundry.js:4406 SyntaxError: An error occurred while rendering MonsterBlock5e 91: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at duplicate (foundry.js:931)
    at MonsterBlock5e.getData (monsterblock.js:60)
    at MonsterBlock5e._render (foundry.js:4434)
    at MonsterBlock5e._render (foundry.js:5088)
    at MonsterBlock5e._render (foundry.js:16570)
    at MonsterBlock5e.render (foundry.js:4404)
    at MonsterBlock5e.render (foundry.js:5553)
    at Token._onClickLeft2 (foundry.js:44654)
    at MouseInteractionManager.callback (foundry.js:35797)
(anonymous) @ foundry.js:4406
Promise.catch (async)
render @ foundry.js:4404
render @ foundry.js:5553
_onClickLeft2 @ foundry.js:44654
callback @ foundry.js:35797
_handleClickLeft2 @ foundry.js:35999
_handleMouseDown @ foundry.js:35961
a.emit @ index.js:181
r.dispatchEvent @ InteractionManager.ts:1106
r.processPointerDown @ InteractionManager.ts:1307
t.recursiveFindHit @ TreeSearch.ts:173
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.findHit @ TreeSearch.ts:200
r.processInteractive @ InteractionManager.ts:1177
r.onPointerDown @ InteractionManager.ts:1252
foundry.js:11253 Uncaught (in promise) TypeError: Cannot read property 'updateEmbeddedEntity' of undefined
    at Token.update (foundry.js:11253)
    at Actor5e.update (foundry.js:30809)
    at MonsterBlock5e.prepFlags (monsterblock.js:1009)
    at new MonsterBlock5e (monsterblock.js:18)
    at Actor5e.get sheet [as sheet] (foundry.js:28787)
    at Token._onClickLeft2 (foundry.js:44653)
    at MouseInteractionManager.callback (foundry.js:35797)
    at MouseInteractionManager._handleClickLeft2 (foundry.js:35999)
    at MouseInteractionManager._handleMouseDown (foundry.js:35961)
    at Token.a.emit (index.js:181)
update @ foundry.js:11253
update @ foundry.js:30809
prepFlags @ monsterblock.js:1009
MonsterBlock5e @ monsterblock.js:18
get sheet @ foundry.js:28787
_onClickLeft2 @ foundry.js:44653
callback @ foundry.js:35797
_handleClickLeft2 @ foundry.js:35999
_handleMouseDown @ foundry.js:35961
a.emit @ index.js:181
r.dispatchEvent @ InteractionManager.ts:1106
r.processPointerDown @ InteractionManager.ts:1307
t.recursiveFindHit @ TreeSearch.ts:173
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.findHit @ TreeSearch.ts:200
r.processInteractive @ InteractionManager.ts:1177
r.onPointerDown @ InteractionManager.ts:1252
Promise.then (async)
MonsterBlock5e @ monsterblock.js:18
get sheet @ foundry.js:28787
_onClickLeft2 @ foundry.js:44653
callback @ foundry.js:35797
_handleClickLeft2 @ foundry.js:35999
_handleMouseDown @ foundry.js:35961
a.emit @ index.js:181
r.dispatchEvent @ InteractionManager.ts:1106
r.processPointerDown @ InteractionManager.ts:1307
t.recursiveFindHit @ TreeSearch.ts:173
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.findHit @ TreeSearch.ts:200
r.processInteractive @ InteractionManager.ts:1177
r.onPointerDown @ InteractionManager.ts:1252

**Comment by zeel01** [comment]
Typically this error will occur, and then the sheet will re-attempt to render, having fixed the missing data that causes the error. I'm not sure how to stop the error from happening in the first place, but it normally doesn't result in the sheet failing to open.

If this still causes a complete failure to render in v2.2.6, there must be something more to it than I've seen previously. Please open a new issue with as much information about the problem as possible.
- Browser (Chrome, Firefox, Electron app)
- Is your server the app, self hosted, or hosted somewhere like The Forge?
- Please check that this issue occurs when Monster Blocks is the only module enabled
- Does this effect all or only some monsters?
- What monster(s) cause this? Where did they come from? R20, DDB, homebrew?
 - If possible include exported JSON for an effected creature.
- Include not only the error message, but a few regular console messages from right before/after so I can see if there is something else happening that might effect the rendering.
- Has Monster Blocks worked for you previously, or was this the first time you tried it? If so, has anything other than Core/System/Module versions changed since the last time it worked correctly?
